### ISSUE TITLE
Code sample indentation is off

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/eleventy-patterns#15]
This is a common problem in our projects:

<img width="478" alt="Screen Shot 2019-12-10 at 2 38 15 PM" src="https://user-images.githubusercontent.com/69633/70575172-c6878c00-1b5a-11ea-8c15-b839fd99f2d9.png">

**Comment by Paul-Hebert** [comment]
It's weird that we're having this issue. We're using the [`pretty`](https://github.com/jonschlinkert/pretty) library to address this. I compared our implementation here with previous projects that don't have this issue and it's unclear why it's not working here. This will require more digging 🤔

**Comment by tylersticka** [comment]
I notice here that there is indentation before `{{~`:

https://github.com/cloudfour/eleventy-patterns/blob/a631d06d5626eb9b67c87458cfbdc098d9de2e4a/src/_includes/layouts/pattern-example.hbs#L13-L15

I looked at a previous project and that was all on one line.

It's also possible that something about Handlebars is making this difficult... speaking anecdotally, every Handlebars project I've worked on with code previews has had some sort of indentation weirdness. It might be a coincidence, but Eleventy lets us mix and match template engines, so we could always give another a try if we wanted to.

**Comment by Paul-Hebert** [comment]
Good point about the indentation. I'd tried putting it all on one line but it continues to behave the same. 

Also good point about template engines. 

Looking at the [`pretty` source](https://github.com/jonschlinkert/pretty/blob/master/index.js) it looks like it doesn't do what I thought it did in regards to whitespace and indentation.

I've also fixed similar problems in the past with custom JS, and it's not too hard. I'm just confused about why we're having this problem here but not in the other project I viewed... I'll do some more investigation
